// Supplier references are verified directly from official supplier websites.
// They are kept separate from the store's physical inventory and operational stock.

function mkRefVariations(prefix, sizes, colors) {
  return colors.flatMap((color) =>
    sizes.map((size) => ({
      id: `${prefix}-${size.toLowerCase().replace(/[^a-z0-9]/g, "")}-${color.toLowerCase().replace(/[^a-z0-9]/g, "")}`,
      size,
      color,
      physical: 0,
      reserved: 0,
    }))
  );
}

export const SUPPLIER_REFERENCES = [
  {
    id: "ref-md-ana",
    name: "Conjunto Ana",
    brand: "Maria Dondoca",
    category: "Conjuntos",
    code: "MD-ANA",
    supplierReference: null,
    sourceType: "supplier-reference",
    dataKind: "supplier-reference",
    sourceUrl: "https://www.mariadondoca.com.br/produtos/conjunto-ana-ovw0j/",
    sourceCheckedAt: "2026-09-10",
    price: 359.8,
    supplierPrice: 359.8,
    pixPrice: 341.81,
    supplierPixPrice: 341.81,
    supplierInstallments: "3x de R$ 119,93 sem juros",
    photos: [
      "https://acdn-us.mitiendanube.com/stores/006/914/055/products/img_7712-5ac647bcad088894c617890105753819-640-0.webp",
    ],
    imageOrigin: "Página oficial do produto na loja online Maria Dondoca. Permissão de revenda/demonstração conforme relacionamento comercial informado.",
    description: "O Conjunto Ana traz uma proposta casual e moderna, composto por camisa de mangas curtas e short com cintura elástica. As listras laterais contrastantes acrescentam personalidade ao visual.",
    sizes: ["P", "M", "G"],
    colors: ["Bege", "Marrom"],
    variations: mkRefVariations("ref-md-ana", ["P", "M", "G"], ["Bege", "Marrom"]),
  },
  {
    id: "ref-md-liz",
    name: "Conjunto Liz",
    brand: "Maria Dondoca",
    category: "Conjuntos",
    code: "MD-LIZ",
    supplierReference: null,
    sourceType: "supplier-reference",
    dataKind: "supplier-reference",
    sourceUrl: "https://www.mariadondoca.com.br/produtos/conjunto-liz-13tma/",
    sourceCheckedAt: "2026-09-10",
    price: 379.8,
    supplierPrice: 379.8,
    pixPrice: 360.81,
    supplierPixPrice: 360.81,
    supplierInstallments: "3x de R$ 126,60 sem juros",
    photos: [
      "https://acdn-us.mitiendanube.com/stores/006/914/055/products/img_7726-0becb8a6716bc9068f17890039069287-640-0.webp",
    ],
    imageOrigin: "Página oficial do produto na loja online Maria Dondoca.",
    description: "O Conjunto Liz combina leveza e modernidade em uma produção elegante. A blusa assimétrica traz acabamento contrastante, enquanto a calça pantalona possui modelagem ampla e confortável.",
    sizes: ["P", "M", "G"],
    colors: ["Mescla/Pink", "Mescla/Lima"],
    variations: mkRefVariations("ref-md-liz", ["P", "M", "G"], ["Mescla/Pink", "Mescla/Lima"]),
  },
  {
    id: "ref-pb-92083",
    name: "Calça Cintura Perfeita Modeladora e Sofisticada",
    brand: "Pit Bull Jeans",
    category: "Calças",
    code: "92083",
    supplierReference: "92083",
    sourceType: "supplier-reference",
    dataKind: "supplier-reference",
    sourceUrl: "https://www.pitbulljeans.com.br/calca-cintura-perfeita-modeladora-e-sofisticada-pit-bull-jeans-premium-92083-p37746",
    sourceCheckedAt: "2026-09-10",
    price: 279.99,
    supplierPrice: 279.99,
    pixPrice: 251.99,
    supplierPixPrice: 251.99,
    supplierInstallments: "até 4x de R$ 70,00 sem juros",
    photos: [
      "https://dzg5mdpaq0k37.cloudfront.net/Custom/Content/Products/37/74/37746_calca-cintura-perfeita-modeladora-e-sofisticada-pit-bull-jeans-premium-92083_l1_639237707317719887.webp",
    ],
    imageOrigin: "Página oficial do produto na loja Pit Bull Jeans Premium.",
    description: "Desenvolvida para valorizar a cintura e o quadril com modelagem anatômica, feminina e marcante. Cós largo com fechamento triplo, botões metálicos, rebites com strass e bojo bundex removível.",
    sizes: ["38", "40", "42", "44", "46"],
    colors: ["Azul Escuro"],
    variations: mkRefVariations("ref-pb-92083", ["38", "40", "42", "44", "46"], ["Azul Escuro"]),
  },
  {
    id: "ref-pb-90666",
    name: "Calça Skinny Preta Modeladora e Sofisticada",
    brand: "Pit Bull Jeans",
    category: "Calças",
    code: "90666",
    supplierReference: "90666",
    sourceType: "supplier-reference",
    dataKind: "supplier-reference",
    sourceUrl: "https://www.pitbulljeans.com.br/calca-skinny-preta-modeladora-e-sofisticada-pit-bull-jeans-90666-p29782",
    sourceCheckedAt: "2026-09-10",
    price: 149.99,
    supplierPrice: 149.99,
    pixPrice: 134.99,
    supplierPixPrice: 134.99,
    supplierInstallments: "até 3x de R$ 50,00 sem juros",
    photos: [
      "https://dzg5mdpaq0k37.cloudfront.net/Custom/Content/Products/29/78/29782_calca-skinny-preta-modeladora-e-sofisticada-pit-bull-jeans-90666_l1_639075400558176450.webp",
    ],
    imageOrigin: "Página oficial do produto na loja Pit Bull Jeans Premium.",
    description: "Modelagem skinny estruturada que define as curvas e alonga visualmente a silhueta, com bojo bundex removível, cintura com ajuste firme e acabamento All Black impecável.",
    sizes: ["36", "38", "40", "42", "44"],
    colors: ["Preto"],
    variations: mkRefVariations("ref-pb-90666", ["36", "38", "40", "42", "44"], ["Preto"]),
  },
  {
    id: "ref-rh-58019",
    name: "Calça Flare Jeans",
    brand: "Rhero",
    category: "Calças",
    code: "58019",
    supplierReference: "58019",
    sourceType: "supplier-reference",
    dataKind: "supplier-reference",
    sourceUrl: "https://rhero.com.br/58019-calca-jeans-1225342965/p",
    sourceCheckedAt: "2026-09-10",
    price: 359.9,
    supplierPrice: 359.9,
    pixPrice: null,
    supplierPixPrice: null,
    supplierInstallments: "Consulte opções com a RS Modas",
    photos: [
      "https://pub-7342f30b43dc4809821fd7b96d67a18d.r2.dev/rhero-converter/58019-cal%C3%A7a-flare-azul-m%C3%A9dio-rhero-1.jpg",
    ],
    imageOrigin: "Página oficial do produto no site Rhero Jeans.",
    description: "Calça flare jeans de cintura alta, justa até o joelho e abrindo da panturrilha para baixo. O jeans tem elastano, com recorte em coração que levanta o bumbum e bojo removível.",
    sizes: ["36", "38", "40", "42", "44", "46", "48"],
    colors: ["Azul Médio"],
    variations: mkRefVariations("ref-rh-58019", ["36", "38", "40", "42", "44", "46", "48"], ["Azul Médio"]),
  },
];
